name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 13
      - name: Install dependencies
        run: npm i
      - name: Run lint
        run: npm run lint
