name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on Node ${{ matrix.node_version }} with Redis ${{ matrix.redis_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['10', '12', '13']
        redis_version: ['4', '5']

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node_version }}

    - name: Setup Redis ${{ matrix.redis_version }}
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: ${{ matrix.redis_version }}

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm run test
