name: Test coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: 5
      - name: Install dependencies
        run: npm i
      - name: Run Coveralls
        run: npx jest --forceExit --coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
